dist: xenial
language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"

services:
  - xvfb

before_install:
  - "export DISPLAY=:99.0"
  - sudo apt-get install gfortran libblas-dev liblapack-dev mpich libmpich-dev

install:
  - pip install numpy scipy matplotlib pyDOE mpi4py nose codecov
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=bet --cover-erase --cover-html
  - mpirun -n 2 nosetests
  - pip uninstall -y mpi4py
  - nosetests

# notification settings
notifications:
    email:
        recipients:
            - steve.a.mattis@gmail.com
            - lichgraham@gmail.com
            - scottw13@gmail.com
            - michael.pilosov@ucdenver.edu
        on_success: change
        on_failure: always

# whitelist
branches:
    only:
        - master

# Push the results back to codecov
after_success:
  - codecov
