language: python
python:
    #- "2.6"
    - "2.7"
    #- "3.2"
    #- "3.3"
    #- "3.4"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get install gfortran libblas-dev liblapack-dev mpich2 libmpich2-dev
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose
  - pip install pyDOE mpi4py
  - python setup.py install

script:
  - nosetests
  - mpirun -n 2 nosetests
  - pip uninstall -y mpi4py
  - nosetests

# notification settings
notifications:
    email:
        recipients:
            - steve.a.mattis@gmail.com
            - lichgraham@gmail.com
            - scottw13@gmail.com
            - michael.pilosov@ucdenver.edu
        on_success: change
        on_failure: always
# whitelist
branches:
    only:
        - master
        - v2_master
