language: python
python:
    #- "2.6"
    - "2.7"
    #- "3.2"
    #- "3.3"
    #- "3.4"
# command to install dependencies
before_install:
    - sudo apt-get install gfortran libblas-dev liblapack-dev mpich2 libmpich2-dev python-dev python-numpy python-scipy python-matplotlib python-nose python-pip
    - pip install pyDOE mpi4py

# install package:
    - python setup.py install
# script to run before running tests
before_script:
    - mkdir -p shippable/testresults
# command to run tests
script:
    - nosetests --with-xunit --xunit-file=shippable/testresults/nosetests_mpi4py_serial.xml
    - mpirun -n 2 nosetests --with-xunit --xunit-file=shippable/testresults/nosetests_mpi4py_parallel.xml
    - pip uninstall -y mpi4py
    - nosetests --with-xunit --xunit-file=shippable/testresults/nosetests_nompi4py.xml
# notification settings
notifications:
    email:
        recipients:
            - steve.a.mattis@gmail.com
            - lichgraham@gmail.com
        on_success: change
        on_failure: always
# whitelist
branches:
    only:
        - master

