dist: xenial
language: python

python:
    - "3.6"
    - "3.7"

services:
  - xvfb

before_install:
  - "export DISPLAY=:99.0"
  - sudo apt-get install gfortran libblas-dev liblapack-dev mpich libmpich-dev

install:
  - pip install matplotlib mpi4py nosetest codecov pytest pytest-cov
  - python setup.py install

script:
  - pytest --cov=./bet/ ./test/

# notification settings
notifications:
    email:
        recipients:
            - steve.a.mattis@gmail.com
        on_success: change
        on_failure: always

# whitelist
branches:
    only:
        - v3-steve

# Push the results back to codecov
after_success:
  - codecov
