# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: 
      - '*'
  schedule:
      - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gfortran libblas-dev liblapack-dev mpich libmpich-dev
        pip3 install git+https://github.com/CU-Denver-UQ/LUQ
        pip3 install .
        pip3 install codecov pytest pytest-cov Sphinx sphinx_rtd_theme
 
    - name: Serial tests
      run: pytest --cov=./bet/ ./test/

    - name: Parallel tests
      run: mpirun -n 2 pytest  ./test/

    - name: Serial tests (w/o MPI)    
      run: |
        pip3 uninstall -y mpi4py
        pytest ./test/

    - name: Documentation
      run: |
        sphinx-apidoc -f -o doc bet
        cd doc/
        make html
        make html
        cd ..

